import java_cup.runtime.*;
terminal MAS, MENOS, POR,DIV;
terminal Integer NUMERO;

non terminal lista;
non terminal Integer exp;

precedence left MAS, MENOS;
precedence left POR, DIV;

lista ::= exp lista 
        | exp:e {:System.out.print(e);:} ;

exp ::= MAS exp:e1 exp:e2 {:RESULT = e1+e2;:}
    |   MENOS exp:e1 exp:e2 {:RESULT = e1-e2;:}
    |   POR exp:e1 exp:e2 {:RESULT = e1*e2;:}
    |   DIV exp:e1 exp:e2 {:RESULT = e1/e2;:}
    |   NUMERO:n {:RESULT= n;:} ;