
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 10;
  public static final int POR = 25;
  public static final int GE = 18;
  public static final int FOR = 6;
  public static final int CP = 9;
  public static final int AND = 20;
  public static final int IGUAL = 27;
  public static final int LT = 17;
  public static final int STRINGTEXT = 34;
  public static final int OR = 21;
  public static final int DIV = 26;
  public static final int NUM = 31;
  public static final int CHARTEXT = 35;
  public static final int CC = 11;
  public static final int IF = 2;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PRECEDENCIASTRING = 40;
  public static final int COMA = 30;
  public static final int MENOS = 24;
  public static final int IDENT = 32;
  public static final int EQ = 14;
  public static final int MENOSUNARIO = 28;
  public static final int CLL = 13;
  public static final int REAL = 33;
  public static final int NO = 22;
  public static final int ELSE = 3;
  public static final int WHILE = 5;
  public static final int CASTINGCHAR = 38;
  public static final int NE = 15;
  public static final int CASTINGFLOAT = 37;
  public static final int ALL = 12;
  public static final int AP = 8;
  public static final int GT = 19;
  public static final int LENGTH = 39;
  public static final int PRINT = 7;
  public static final int DO = 4;
  public static final int PYC = 29;
  public static final int CASTINGINT = 36;
  public static final int MAS = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "PRINT",
  "AP",
  "CP",
  "AC",
  "CC",
  "ALL",
  "CLL",
  "EQ",
  "NE",
  "LE",
  "LT",
  "GE",
  "GT",
  "AND",
  "OR",
  "NO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUAL",
  "MENOSUNARIO",
  "PYC",
  "COMA",
  "NUM",
  "IDENT",
  "REAL",
  "STRINGTEXT",
  "CHARTEXT",
  "CASTINGINT",
  "CASTINGFLOAT",
  "CASTINGCHAR",
  "LENGTH",
  "PRECEDENCIASTRING"
  };
}

