
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 10;
  public static final int AND = 8;
  public static final int MENOR = 17;
  public static final int IDENT = 27;
  public static final int ELSE = 20;
  public static final int CP = 3;
  public static final int PYC = 13;
  public static final int IGUAL = 15;
  public static final int WHILE = 21;
  public static final int EQLN = 6;
  public static final int O = 12;
  public static final int IF = 19;
  public static final int CC = 5;
  public static final int POR = 11;
  public static final int AP = 2;
  public static final int DO = 22;
  public static final int MENOSUNARIO = 26;
  public static final int MAYOR = 18;
  public static final int EOF = 0;
  public static final int DIFERENTE = 16;
  public static final int EX = 7;
  public static final int DIV = 14;
  public static final int AC = 4;
  public static final int PRINT = 24;
  public static final int error = 1;
  public static final int ENTERO = 25;
  public static final int FOR = 23;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AP",
  "CP",
  "AC",
  "CC",
  "EQLN",
  "EX",
  "AND",
  "MAS",
  "MENOS",
  "POR",
  "O",
  "PYC",
  "DIV",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "ENTERO",
  "MENOSUNARIO",
  "IDENT"
  };
}

