
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int COMA = 4;
  public static final int CC = 3;
  public static final int error = 1;
  public static final int AC = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AC",
  "CC",
  "COMA",
  "NUMERO"
  };
}

