
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 4;
  public static final int POR = 11;
  public static final int CHAR = 21;
  public static final int ENTERO = 33;
  public static final int DIFERENTE = 16;
  public static final int O = 12;
  public static final int INT = 32;
  public static final int FOR = 30;
  public static final int CP = 3;
  public static final int AND = 8;
  public static final int IGUAL = 15;
  public static final int EQLN = 6;
  public static final int CASTCHAR = 24;
  public static final int DIV = 14;
  public static final int CC = 5;
  public static final int IF = 26;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int EX = 7;
  public static final int MENOS = 10;
  public static final int MENOR = 17;
  public static final int IDENT = 35;
  public static final int MENOSUNARIO = 34;
  public static final int REAL = 20;
  public static final int MAYOR = 18;
  public static final int CASTINT = 23;
  public static final int ELSE = 27;
  public static final int WHILE = 28;
  public static final int FLOAT = 22;
  public static final int UNICODE = 37;
  public static final int ASCII = 36;
  public static final int AP = 2;
  public static final int PRINT = 31;
  public static final int DO = 29;
  public static final int CASTFLOAT = 25;
  public static final int PYC = 13;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AP",
  "CP",
  "AC",
  "CC",
  "EQLN",
  "EX",
  "AND",
  "MAS",
  "MENOS",
  "POR",
  "O",
  "PYC",
  "DIV",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "COMA",
  "REAL",
  "CHAR",
  "FLOAT",
  "CASTINT",
  "CASTCHAR",
  "CASTFLOAT",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "INT",
  "ENTERO",
  "MENOSUNARIO",
  "IDENT",
  "ASCII",
  "UNICODE"
  };
}

